---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_cache:
  - rm -vrf packages/*/node_modules/@perfyjs
  - rm -vrf $(npm config get cache)/_logs

cache:
  directories:
    - $(npm config get cache)
    - node_modules
    - packages/core/node_modules
    - packages/cli/node_modules
    - packages/example/node_modules
    - packages/reporter-web/node_modules
    - packages/types/node_modules

jobs:
  include:
    - stage: test
      env: PACKAGE=core
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ../..
    -
      env: PACKAGE=example
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ../..
    -
      env: PACKAGE=reporter-web
      addons:
        chrome: beta
      before_install:
        - export CHROME_BIN="google-chrome-beta"
        - export KARMA_SINGLE_RUN=true

        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ../..
    -
      env: PACKAGE=types
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ../..
