---
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - export CHROME_BIN=chromium-browser
  - mkdir -p ~/.config
  - echo "--no-sandbox" > ~/.config/chromium-flags.conf
  - export KARMA_SINGLE_RUN=true

before_script:
  - npm run install:packages
  - npm run install:reporter-web

cache:
  directories:
  - node_modules
  - packages/reporter-web/node_modules
