---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_cache:
  - rm -vrf packages/*/node_modules/@perfyjs
  - rm -vrf $(npm config get cache)/_logs

cache:
  directories:
    - $(npm config get cache)
    - node_modules

jobs:
  include:
    - stage: test
      env: PACKAGE=core
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ..
    -
      env: PACKAGE=example
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ..
    -
      env: PACKAGE=reporter-web
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ..
    -
      env: PACKAGE=types
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ..
