---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_cache:
  - rm -rf $(npm config get cache)/_logs

cache:
  directories:
    - $(npm config get cache)
    - node_modules

jobs:
  include:
    - stage: prepare cache
      install: npm i -g npm
      script: skip

    - stage: test
      env: PACKAGE=core

      before_script:
        - npm run bootstrap
        - npm run build
        - cd packages/$PACKAGE
      script:
        - npm run lint
        - npm run test

      before_cache:
        - cd ..
