---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_cache:
  - cd ..
  - rm -rf $(npm config get cache)/_logs

cache:
  directories:
    - $(npm config get cache)
    - node_modules
    - packages/core/node_modules
    - packages/cli/node_modules
    - packages/example/node_modules
    - packages/reporter-web/node_modules
    - packages/types/node_modules

jobs:
    - stage: test
      env: PACKAGE=core
      cache:
        directories:
      before_script:
        - npm run bootstrap
        - cd packages/$PACKAGE
      script:
        - npm run lint
        - npm run test
    -
      env: PACKAGE=types
      cache:
        directories:
      before_script:
        - npm run bootstrap
        - cd packages/$PACKAGE
      script:
        - npm run lint
        - npm run test
