---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache:
  directories:
  - $(npm config get cache)
  - node_modules
  - packages/cli/dist
  - packages/cli/node_modules
  - packages/core/dist
  - packages/core/node_modules
  - packages/types/dist
  - packages/types/node_modules

jobs:
  include:
    - stage: prepare cache
      script:
        - npm run install:packages
        - npm run build

    #
    #
    #

    - stage: test
      env: PACKAGE=cli
      install: skip
      before_script: cd packages/$PACKAGE
      before_cache:
        # clean test output
        - npm run prebuild:test
    -
      env: PACKAGE=core
      install: skip
      script:
        - npm run install:packages
        - npm run build
      before_script: cd packages/$PACKAGE
      before_cache:
        # clean test output
        - npm run prebuild:test
    -
      env: PACKAGE=example
      install: skip
      before_script: cd packages/$PACKAGE
    -
      env: PACKAGE=reporter-web
      addons:
        chrome: beta
      install:
        - export CHROME_BIN="google-chrome-beta"
        - export KARMA_SINGLE_RUN=true

        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      before_script:
        - cd packages/$PACKAGE
    -
      env: PACKAGE=types
      install: skip
      before_script: cd packages/$PACKAGE

    #
    #
    #

    - stage: deploy
      addons:
        chrome: beta
      install:
        - export CHROME_BIN=$(which google-chrome-beta)

        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
      before_script: cd packages/example
      script: npm run perf:test
      after_success:
        - npm run perfy -- update
        - npm run perfy -- report
      before_deploy:
        - mkdir -p ghpages/example
        - mv perfy_report ghpages/example
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: ghpages
        github-token: $GITHUB_TOKEN
        on:
          branch: master
