---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

addons:
  chrome: beta

node_js: stable

cache:
  directories:
  - $(npm config get cache)
  - node_modules
  - packages/cli/node_modules
  - packages/core/node_modules

before_install:
  - export CHROME_BIN="google-chrome-beta"
  - export KARMA_SINGLE_RUN=true

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - stage: prepare cache
      before_script: nvm i 7
      script: npm run install:packages
    - stage: test
      install: true
      before_script: cd packages/cli
    -
      install: true
      before_script: cd packages/core
    # -
    #   install: true
    #   before_script: cd packages/example
    # -
    #   install: true
    #   before_script: cd packages/reporter-web
