---
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - npm run install:packages
  - npm run install:reporter-web

cache:
  directories:
  - node_modules
  - packages/reporter-web/node_modules
