---
dist: trusty
sudo: false
git:
  depth: 1

services:
  - docker

env:
  - DOCKER_IMAGE="$DOCKER_USERNAME/travis-ci-perfy:$TRAVIS_BRANCH"

jobs:
  include:

    - stage: build docker image
      install: skip
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t travis-ci-perfy:$TRAVIS_BRANCH .
        - docker images
        - docker tag travis-ci-perfy:$TRAVIS_BRANCH $DOCKER_IMAGE
        - docker push $DOCKER_IMAGE
    - stage: testing docker
      script:
        - docker run --rm $DOCKER_IMAGE npm run build
        - docker run --rm $DOCKER_IMAGE npm test
