---
language: node_js
sudo: required
git:
  depth: 1
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js: stable

before_install:
  - export CHROME_BIN=google-chrome-stable
  - mkdir -p ~/.config
  - echo "--no-sandbox --headless --disable-gpu" > ~/.config/chromium-flags.conf
  - export KARMA_SINGLE_RUN=true


before_script:
  - npm run install:packages
  - npm run install:reporter-web

cache:
  directories:
  - node_modules
  - packages/reporter-web/node_modules
