---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache:
  directories:
  - $(npm config get cache)
  - node_modules
  - packages/cli/node_modules
  - packages/cli/dist
  - packages/core/node_modules
  - packages/core/dist
  - packages/example/node_modules
  - packages/example/dist
  - packages/reporter-web/node_modules
  - packages/reporter-web/dist
  - packages/types/node_modules
  - packages/types/dist


jobs:
  include:
    - stage: prepare cache
      # lerna is not working properly with npm@5
      # We use npm@4 though node@<7.10
      before_script: nvm i 7
      script: npm run install:packages
    - stage: test
      install: skip
      before_script: cd packages/cli
      before_cache:
        # clean test output
        - rm -rf prebuild:test
    -
      install: skip
      before_script: cd packages/core
      before_cache:
        # clean test output
        - rm -rf prebuild:test
    -
      install: skip
      before_script: cd packages/example
    -
      install: skip
      before_script: cd packages/types
    -
      addons:
        chrome: beta
      install:
        - export CHROME_BIN="google-chrome-beta"
        - export KARMA_SINGLE_RUN=true

        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start

      before_script:
        # As we compiled with node@7.10 we have to
        # use it to keep node-sass happy.
        - nvm i 7
        - cd packages/reporter-web
    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        github-token: $GITHUB_TOKEN
        on:
          branch: master
