---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_cache:
  - rm -rf packages/*/node_modules/@perfyjs
  - rm -rf $(npm config get cache)/_logs

cache:
  directories:
    - $(npm config get cache)
    - node_modules
    - packages/core/node_modules
    - packages/cli/node_modules
    - packages/example/node_modules
    - packages/reporter-web/node_modules
    - packages/types/node_modules

jobs:
  include:
    - stage: test
      env: PACKAGE=core
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ..
    -
      env: PACKAGE=types
      before_script:
        - npm run bootstrap
      script:
        - cd packages/$PACKAGE
        - npm run lint
        - npm run test
        - cd ..
