---
language: node_js
sudo: false
git:
  depth: 1
addons:
  - chrome

node_js: stable

before_script:
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  - npm run install:packages
  - npm run install:reporter-web

cache:
  directories:
  - node_modules
  - packages/reporter-web/node_modules
