---
dist: trusty
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

cache:
  directories:
    - $(npm config get cache)
    - node_modules

jobs:
  include:
    - stage: prepare cache
      install: npm i -g npm
      script: skip

    - stage: test
      env: PACKAGE=cli
      before_script:
        - npm run bootstrap
        - cd packages/$PACKAGE
      script:
        - npm run lint
        - npm run test
