---
language: node_js
sudo: false
git:
  depth: 1

node_js: stable

before_script:
  - export CHROME_BIN=chromium-browser

  - npm run install:packages
  - npm run install:reporter-web

cache:
  directories:
  - node_modules
  - packages/reporter-web/node_modules
